version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: goorm-class
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    ports:
      - 16686:16686
      - 4318:4318
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
volumes:
  db_data:
