name: Go CI

on:
  push:
    branches: [dev, chore/13/gotestWorkflow]
  pull_request:
    branches: [dev, chore/13/gotestWorkflow]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.22"

      - name: install dependencies
        run: go mod download

      - name: running test
        run: go test -v ./...
