name: Go CI

on:
  push:
    branches: [dev, chore/13/gotestWorkflow]
  pull_request:
    branches: [dev, chore/13/gotestWorkflow]
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
          - 4318:4318 # Jaeger 에이전트 포트
          - 16686:16686 # Jaeger UI 포트
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.22"
      - name: install dependencies
        run: go mod download
      - name: running test
        run: go test -v ./...
